name: GitHub Actions Demo
on: 
  push:
    branches:
      - master
jobs:
  update-qa:
    name: Deploy QA - Branch development pushed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push
      run: |
        git push origin qa
      
