name: GitHub Actions Demo
on: 
  push:
    branches:
      - master
jobs:
  update-qa:
    name: Deploy QA - Branch development pushed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push
      uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/master'
      with: 
        branch: qa
        force: 1
      
